// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3n-PW4unmDoR2VgPhLS50USesB_DKw4',
    appId: '1:566718359946:android:3958e4c6967c72cfd60073',
    messagingSenderId: '566718359946',
    projectId: 'flutter-firebase-b8137',
    storageBucket: 'flutter-firebase-b8137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRR_Zql14GXBWWIwDTECL-bc3Xi-WXSPE',
    appId: '1:566718359946:ios:bdd3e1add1242a03d60073',
    messagingSenderId: '566718359946',
    projectId: 'flutter-firebase-b8137',
    storageBucket: 'flutter-firebase-b8137.appspot.com',
    androidClientId: '566718359946-s6ne9po3jt9eg7jt39id56h9aje0rfsh.apps.googleusercontent.com',
    iosClientId: '566718359946-7naniftqc3u6p51odl5bku2jht42btsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.unigem.unigemDemo',
  );
}
